### ISSUE TITLE
NPE on GvrLayout

### ISSUE THREAD

**Issue by Oleur** [googlevr/gvr-unity-sdk#438]
Hi! 

Several of my users are getting this crash: 
``
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.Display.isValid()' on a null object reference
	at com.google.vr.ndk.base.GvrLayout$PresentationHelper.isValidExternalDisplay(SourceFile:1230)
	at com.google.vr.ndk.base.GvrLayout$PresentationHelper.onDisplayAdded(SourceFile:1132)
	at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:464)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5442)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
``

Devices: **Xiaomi MI MAX** and **Xiaomi Redmi Note 3** both on Android 6.0
Unity version     : 5.5.0f3

Any idea how to fix that ? 

Thanks a lot

Julien

**Comment by bopangzz** [comment]
Can you get a full log by chance? I will take a look and get back to you once I have more info.

**Comment by Oleur** [comment]
This is the best I can do about the crash, I do not have much more information: 

```txt
Fatal Exception: java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 5.5.0f3
Device model      : Xiaomi MI MAX
Device fingerprint: Xiaomi/hydrogen/hydrogen:6.0.1/MMB29M/V8.1.6.0.MBCMIDI:user/release-keys

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.Display.isValid()' on a null object reference
       at com.google.vr.ndk.base.GvrLayout$PresentationHelper.isValidExternalDisplay(SourceFile:1230)
       at com.google.vr.ndk.base.GvrLayout$PresentationHelper.onDisplayAdded(SourceFile:1132)
       at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:464)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5442)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

**Comment by bopangzz** [comment]
Thanks! We will look into this.

**Comment by miraleung** [comment]
@Oleur Is this a Cardboard app, and are you able to repro locally? What are the minimum and target Android API levels in your manifest?

**Comment by jamesem** [comment]
Hi, I have seen this same issue, in a Unity Cardboard app.

Steps to reproduce:
1. Device: Google Pixel
2. Open the VR app, so you can see the 'split screen', with a settings 'cog' at the bottom center of the screen
3. Click the settings 'cog' to open a dialog, title "Configure", message "Set up your viewer for the best experience.", buttons "CANCEL", "SETUP"
4. Click "SETUP" to open the settings panel
5. Press the software 'back' button (top left)
6. App crashes

 E/AndroidRuntime: FATAL EXCEPTION: main
                                               Process: com.____.______, PID: 501
                                               java.lang.Error: FATAL EXCEPTION [main]
                                               Unity version     : 5.5.2f1
                                               Device model      : Google Pixel
                                               Device fingerprint: google/sailfish/sailfish:7.1.1/NOF27B/3687361:user/release-keys
                                               
                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.Display.isValid()' on a null object reference
                                                   at com.google.vr.ndk.base.GvrLayout$PresentationHelper.isValidExternalDisplay(GvrLayout.java:804)
                                                   at com.google.vr.ndk.base.GvrLayout$PresentationHelper.onDisplayAdded(GvrLayout.java:706)
                                                   at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:459)
                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                   at android.os.Looper.loop(Looper.java:154)
                                                   at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by jamesem** [comment]
@miraleung was this resolved? I noticed this was an issue which appeared when Unity version 5.5.2f1 was used, as opposed to an earlier version.

**Comment by miraleung** [comment]
I have not been able to repro in the past few releases, so yes, this is fixed.

Please consider upgrading to Unity 5.6 while on 1.40, since we will be removing support for < 5.6 in the next release.

**Comment by miraleung** [comment]
I have not been able to repro in the past few releases, so yes, this is
fixed.

Please consider upgrading to Unity 5.6 while on 1.40, since we will be
removing support for < 5.6 in the next release.
