### ISSUE TITLE
Demo scene crash Unity 5.5.2 GoogleVR 1.30.0

### ISSUE THREAD

**Issue by nathansizemore** [googlevr/gvr-unity-sdk#505]
Loading a demo scene causes crash on application launch.

Unity 5.5.2 macOS (Released Feb 24, 2017)
Target: Android 7.1
Min SDK: Android 6.0

```
--------- beginning of system
03-22 18:50:09.760  4544  7210 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.ra.flamingo/com.google.unity.GoogleUnityActivity (has extras)} from uid 10089 on display 0
03-22 18:50:09.765  4280  4375 D audio_hw_primary: enable_snd_device: snd_device(78: vi-feedback)
03-22 18:50:09.766  4280  4375 D audio_hw_primary: enable_audio_route: usecase(21) apply and update mixer path: spkr-vi-record
03-22 18:50:09.797  4280  4375 D audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback
03-22 18:50:09.816  4544 19377 I ActivityManager: Start proc 4204:com.ra.flamingo/u0a149 for activity com.ra.flamingo/com.google.unity.GoogleUnityActivity
03-22 18:50:09.834  4544  7214 I sensors : batch
03-22 18:50:09.835  4544  7214 I nanohub : queueBatch: sensor=28, handle=31, period=66667000, latency=0
03-22 18:50:09.837  4544  7214 I sensors : activate
03-22 18:50:09.839  4544  7214 I nanohub : queueActivate: sensor=28, handle=31, enable=1
03-22 18:50:09.842  4544  5641 I nanohub : osLog: [BMI160] accSetRate: rate=51200, latency=66666496, state=3
03-22 18:50:09.872  4204  4204 D AndroidRuntime: Shutting down VM
--------- beginning of crash
03-22 18:50:09.873  4204  4204 E AndroidRuntime: FATAL EXCEPTION: main
03-22 18:50:09.873  4204  4204 E AndroidRuntime: Process: com.ra.flamingo, PID: 4204
03-22 18:50:09.873  4204  4204 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.ra.flamingo/com.google.unity.GoogleUnityActivity}: java.lang.ClassNotFoundException: Didn't find class "com.google.unity.GoogleUnityActivity" on path: DexPathList[[zip file "/data/app/com.ra.flamingo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ra.flamingo-1/lib/arm, /data/app/com.ra.flamingo-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
03-22 18:50:09.873  4204  4204 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2567)
03-22 18:50:09.873  4204  4204 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
03-22 18:50:09.873  4204  4204 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
03-22 18:50:09.873  4204  4204 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
03-22 18:50:09.873  4204  4204 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-22 18:50:09.873  4204  4204 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
03-22 18:50:09.873  4204  4204 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
03-22 18:50:09.873  4204  4204 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-22 18:50:09.873  4204  4204 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
03-22 18:50:09.873  4204  4204 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-22 18:50:09.873  4204  4204 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.unity.GoogleUnityActivity" on path: DexPathList[[zip file "/data/app/com.ra.flamingo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ra.flamingo-1/lib/arm, /data/app/com.ra.flamingo-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
03-22 18:50:09.873  4204  4204 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-22 18:50:09.873  4204  4204 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
03-22 18:50:09.873  4204  4204 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-22 18:50:09.873  4204  4204 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
03-22 18:50:09.873  4204  4204 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557)
03-22 18:50:09.873  4204  4204 E AndroidRuntime: 	... 9 more
03-22 18:50:09.875  4544 12011 W ActivityManager:   Force finishing activity com.ra.flamingo/com.google.unity.GoogleUnityActivity
```

**Comment by miraleung** [comment]
Could you please check if you have Assets/Plugins/Android/unitygvractivity.aar and Assets/Plugins/Android/gvr_android_common.aar?

We recommend upgrading to the latest version of 5.6; in an upcoming release, we will be removing support for versions of Unity without the GVR native integration.

**Comment by nathansizemore** [comment]
At that time, Unity 5.6.0f1 had a bug that caused the editor to crash almost 90% of the time for a certain scene, so I rolled back to just use the regular GoogleVR SDK. It has since been resolved in their latest RC, and I'm no longer using 5.5.2.

However, no, at the time, those were not in the project. I'm assuming those are the "plugins" that the editor prompts you to downloaded when you build? If so, the pop up always came up when building, but it was never actually downloaded anything. Just an error saying it couldn't download.

**Comment by miraleung** [comment]
The dialog is a prompt to import GVRBackwardsCompatibility.unitypackage (in Assets/GoogleVR), which has those libraries. They're required to work in versions of Unity w/o the GVR integration, but going with 5.6 is definitely the preferred path. :)
