### ISSUE TITLE
One Plus 3T - Android Version 7.0 - Crash

### ISSUE THREAD

**Issue by tejpratap0** [googlevr/gvr-unity-sdk#507]
I am getting following error on One Plus 3T but same code is working fine on other devices i.e. Nexus 5, Samsung Galaxy etc. It is occurring on both sdk gvr-unity-sdk v1.0 and gvr-unity-sdk v1.3. 

FATAL EXCEPTION: main
                                                   Process: com.google.vr.vrcore, PID: 30940
                                                   java.lang.RuntimeException: Unable to unbind to service com.google.vr.vrcore.common.VrCoreListenerService@97405dd with Intent { cmp=com.google.vr.vrcore/.common.VrCoreListenerService }: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getPackageName()' on a null object reference
                                                       at android.app.ActivityThread.handleUnbindService(ActivityThread.java:3323)
                                                       at android.app.ActivityThread.-wrap28(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1603)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6209)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getPackageName()' on a null object reference
                                                       at android.os.Parcel.readException(Parcel.java:1689)
                                                       at android.os.Parcel.readException(Parcel.java:1636)
                                                       at android.app.INotificationManager$Stub$Proxy.getZenRules(INotificationManager.java:1701)
                                                       at android.app.NotificationManager.getAutomaticZenRules(NotificationManager.java:474)
                                                       at azr.b(PG:389)
                                                       at com.google.vr.vrcore.common.VrCoreListenerService.onUnbind(PG:3259)
                                                       at android.app.ActivityThread.handleUnbindService(ActivityThread.java:3309)
                                                       at android.app.ActivityThread.-wrap28(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1603) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6209) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by miraleung** [comment]
It looks like this is a result of running a Daydream app on a non-Daydream ready phone - the full list of such devices is [here](https://vr.google.com/daydream/phones/). In the meantime, please ensure that the app is built with Cardboard, not Daydream enabled, if you're using a version of Unity with the GVR native integration.

**Comment by tejpratap0** [comment]
I am building app using Unity 5.5.2 and Daydream is not enabled.

**Comment by miraleung** [comment]
OK - have you changed source in the GVR Unity SDK? Which scene or SDK components are you using in this build?

**Comment by tejpratap0** [comment]
I did't changed any source in GVR Unity SDK. I am using GvrViewerMain object with default settings as in shared screenshot.

![1](https://cloud.githubusercontent.com/assets/5173641/24443516/9488e4d0-1480-11e7-9fc3-9f613be9542e.png)


![2](https://cloud.githubusercontent.com/assets/5173641/24443520/9734481e-1480-11e7-9882-b95b314480cf.png)

**Comment by miraleung** [comment]
In that case, could you please capture a full logcat file (adb logcat -c; adb logcat > /path/to/logcat.txt) next time it crashes? The root cause may be elsewhere.

**Comment by tejpratap0** [comment]
Logcat file during crash:
[OnePlusError.txt](https://github.com/googlevr/gvr-unity-sdk/files/885350/OnePlusError.txt)

**Comment by innocuo** [comment]
For what's worth:

I had the exact same thing happening to us, also on a One Plus 3T, same error in log. I didn't have physical access to the phone, so the attached log is all I could get.

I didn't keep track of everything we tried, but I know we tried:
- Unity 5.5.0f3 with Gvr SDK 1.2 (crashes)
- Unity 5.5.0f3 with Gvr SDK 1.3 (crashes)
- Unity 5.6 with Gvr SDK 1.3 (crashes)
- Enable "VR Supported" with no sdk selected on unity and sdk versions mentioned above (crashes)
- Disable "VR Supported" on unity and sdk versions mentioned above  (crashes)
- Disabled "VR Mode Enabled" on unity and sdk versions mentioned above  (crashes)

We even tried compiling JUST the sample scene that comes with the sdk, also crashes.

I didn't see this (no physical access to phone), but the description I got: when you open the app, you get a message about app required Google VR services. If you clicked on settings, it sent you to a settings screen where you could enable the services. If you enable the services, app crashes. Keep it disabled, app gets the popup, but if you dismiss, app runs just fine.

We found no solution, assumed it was a phone issue, as app ran fine on every other phone we tried (Galaxy Note 5, Galaxy Note 4 Edge, One Plus One, Nexus something).

**Comment by tejpratap0** [comment]
@miraleung - Any update!

**Comment by rusmaxham** [comment]
Are you still experiencing this issue with the latest versions of Unity and the GVR SDK for Unity?

**Comment by rusmaxham** [comment]
If you are still experiencing this issue, feel free to reopen with more details.
