### ISSUE TITLE
App crashes on Android 8 Beta when GoogleVR 1.60 is added to Unity 5.6+ project

### ISSUE THREAD

**Issue by cmdr2** [googlevr/gvr-unity-sdk#652]
Hi,

A user reported that Daydream apps built using Unity 5.6+ and GoogleVR SDK 1.60 crash on the Android O (8) Beta. While I understand this is beta and not a critical issue, I thought I'd report it anyway and let you know.

The app seems to crash with a CalledFromWrongThreadException upon starting. Here's the crashlytics report with the stacktrace: https://pastebin.com/raw/NtAQxKsk

    Caused by android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original 
    thread that created a view hierarchy can touch its views.
       at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7275)
       at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1197)
       at android.view.ViewGroup.invalidateChild(ViewGroup.java:5751)
       at android.view.View.invalidateInternal(View.java:15277)
       at android.view.View.invalidate(View.java:15241)
       at android.view.View.invalidate(View.java:15224)
       at android.view.SurfaceView$1.handleMessage(SurfaceView.java:142)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at com.unity3d.player.UnityPlayer$c.run(Unknown Source:20)

For debugging, the user was asked to try number of dummy apps, each one adding a layer of complexity.

1. [PASSES] [empty Unity app, no VR stuff in it](https://www.dropbox.com/s/8iajoarv396ywh7/AndroidO-Test1.apk?dl=0)
2. [PASSES] [empty Unity app, Unity's VR enabled, GoogleVR SDK not imported](https://www.dropbox.com/s/4ums3rbytfmtckl/AndroidO-Test2.apk?dl=0)
3. [PASSES] [empty Unity app, Unity's VR enabled, GoogleVR EditorEmulator added, Controller GameObject not added ](https://www.dropbox.com/s/mxv6kowkm2ucbt3/AndroidO-Test4.apk?dl=0)
4. [CRASHES] [empty Unity app, Unity's VR enabled, GoogleVR EditorEmulator added, Controller added](https://www.dropbox.com/s/qtdaz6zopk8cv1m/AndroidO-Test5.apk?dl=0)

Thanks!

~cmdr2

**Comment by nathanmartz** [comment]
This should be fixed in the current version of Android O.

**Comment by cmdr2** [comment]
Thanks, to confirm - is the fixed version of Android O the current one that's already released, or the next one to be released? I checked back with the user who confirms being on the latest released version.
