### ISSUE TITLE
1.7.0 Keyboard Demo Crashing

### ISSUE THREAD

**Issue by andrelevi** [googlevr/gvr-unity-sdk#699]
Hi, when running the Keyboard demo in the 1.7.0 repo the app crashes immediately with no error in the logs.

I remember I reported a similar issue with the keyboard demo before, and it was then fixed in an update of the DaydreamKeyboard app (I believe).

I now need user input via the Daydream keyboard for my app, so this issue is pretty critical for me.

Thanks!

**Comment by martinbilello** [comment]
Which version of the DD Keyboard and which version of Unity are you using?

**Comment by andrelevi** [comment]
Unity: 2017.1.0p3 OSX
DD Keyboard: 1.8.170718013

Thanks

**Comment by martinbilello** [comment]
I'm able to run the Keyboard Demo on my end with those versions you mentioned.
Would you be able to provide a logcat of the crash run?

**Comment by andrelevi** [comment]
Hi,

```
--------- beginning of main
--------- beginning of system
08-24 10:08:58.543 24483 24500 I Unity   : SystemInfo CPU = ARMv7 VFPv3 NEON, Cores = 4, Memory = 3758mb
08-24 10:08:58.543 24483 24500 I Unity   : SystemInfo ARM big.LITTLE configuration: 2 big (mask: 12), 2 little (mask: 3)
08-24 10:08:58.544 24483 24500 I Unity   : ApplicationInfo com.google.vr.unity.gvrdemo version 1.0 build ff4fd551-5e82-42ef-9a2b-4ff011d4d518
08-24 10:08:58.624 24483 24500 E Unity   : Unable to find AudioPluginOculusSpatializer
08-24 10:08:58.626 24483 24500 E Unity   : Unable to find libaudioplugingvrunity
08-24 10:08:58.631 24483 24500 E Unity   : Unable to find libAudioPluginOculusSpatializer
08-24 10:08:58.661 24483 24500 D Unity   :  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_multisampled_render_to_texture GL_OES_sha
08-24 10:08:58.661 24483 24500 D Unity   : der_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures
08-24 10:09:19.783 24483 24500 I Unity   : Initializing Daydream controller API.
08-24 10:09:19.783 24483 24500 I Unity   :
08-24 10:09:19.783 24483 24500 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
08-24 10:09:19.783 24483 24500 I Unity   :
08-24 10:09:19.887 24483 24500 I Unity   : Creating and initializing GVR API controller object.
08-24 10:09:19.887 24483 24500 I Unity   :
08-24 10:09:19.887 24483 24500 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
08-24 10:09:19.887 24483 24500 I Unity   :
08-24 10:09:19.890 24483 24500 I Unity   : GVR API successfully initialized. Now resuming it.
08-24 10:09:19.890 24483 24500 I Unity   :
08-24 10:09:19.890 24483 24500 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
08-24 10:09:19.890 24483 24500 I Unity   :
08-24 10:09:19.890 24483 24500 I Unity   : GVR API resumed.
08-24 10:09:19.890 24483 24500 I Unity   :
08-24 10:09:19.890 24483 24500 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
08-24 10:09:19.890 24483 24500 I Unity   :
--------- beginning of crash
08-24 10:09:20.296 24483 24500 I Unity   : Calling set input mode: DEFAULT
08-24 10:09:20.296 24483 24500 I Unity   :
08-24 10:09:20.296 24483 24500 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
08-24 10:09:20.296 24483 24500 I Unity   :
```

If I disable the GvrKeyboardManager, the app no longer crashes at start.

Thanks

**Comment by martinbilello** [comment]
Are those 4 lines the only thing you see after the "beginning of crash" line?

**Comment by andrelevi** [comment]
Actually, it seems like a restart of my phone fixed it. Maybe I had some updates queued or something that required a restart. Sorry for taking up your time!

**Comment by andrelevi** [comment]
So it turns out that this crash occurs after a while (I'm not sure of the exact cause), but it is fixed by restarting my phone. I've repeated this cycle 3 times so far.

To answer your last comment, the last log in the logcat I get is:

```
08-26 16:22:33.533  3025  3059 I Unity   : Calling set input mode: DEFAULT
08-26 16:22:33.533  3025  3059 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
08-26 16:22:33.533  3025  3059 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
08-26 16:22:33.533  3025  3059 I Unity   : UnityEngine.Logger:Log(LogType, Object)
08-26 16:22:33.533  3025  3059 I Unity   : UnityEngine.Debug:Log(Object)
08-26 16:22:33.533  3025  3059 I Unity   : Gvr.Internal.AndroidNativeKeyboardProvider:SetInputMode(GvrKeyboardInputMode) (at /Users/andrelevi/Workspace/vr/DrainDead/Assets/GoogleVR/Scripts/Keyboard/Internal/KeyboardProviders/AndroidNativeKeyboardProvider.cs:159)
08-26 16:22:33.533  3025  3059 I Unity   : GvrKeyboard:Start() (at /Users/andrelevi/Workspace/vr/DrainDead/Assets/GoogleVR/Scripts/Keyboard/GvrKeyboard.cs:150)
08-26 16:22:33.533  3025  3059 I Unity   :
08-26 16:22:33.533  3025  3059 I Unity   : (Filename: /Users/andrelevi/Workspace/vr/DrainDead/Assets/GoogleVR/Scripts/Keyboard/Internal/KeyboardProviders/AndroidNativeKeyboardProvider.cs Line: 159)
08-26 16:22:33.533  3025  3059 I Unity   :
```

**Comment by martinbilello** [comment]
Hmm, those lines don't seem to belong to a crash, they are just informative. Are you just filtering for Unity lines? It would be more useful to have a full logcat

**Comment by andrelevi** [comment]
D'oh! Sorry, you are completely right. I've been using an aliased command for so long I totally forgot.

Here are what I believe to be the relevant parts of the logcat:

```
08-28 11:29:26.777  1097  1128 D ApplicationLoaders: ignored Vulkan layer search path /data/app/com.google.android.vr.inputmethod-2/lib/arm:/data/app/com.google.android.vr.inputmethod-2/base.apk!/lib/armeabi-v7a for namespace 0xf51160d0
08-28 11:29:26.830  1097  1128 W libOpenSLES: class OutputMix interface 0 requested but unavailable MPH=28
08-28 11:29:26.830  1097  1128 I libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
08-28 11:29:26.832  1097  1128 D AudioTrack: Client defaulted notificationFrames to 192 for frameCount 384
08-28 11:29:26.917  1097  1097 E art     : No implementation found for void com.google.vr.audio.DeviceInfo.nativeUpdateHeadphoneStateChange(long, int) (tried Java_com_google_vr_audio_DeviceInfo_nativeUpdateHeadphoneStateChange and Java_com_google_vr_audio_DeviceInfo_nativeUpdateHeadphoneStateChange__JI)
08-28 11:29:26.922  1097  1097 D AndroidRuntime: Shutting down VM
--------- beginning of crash
08-28 11:29:26.937  1097  1097 E AndroidRuntime: FATAL EXCEPTION: main
08-28 11:29:26.937  1097  1097 E AndroidRuntime: Process: com.rpgiagames.mygamevr, PID: 1097
08-28 11:29:26.937  1097  1097 E AndroidRuntime: java.lang.Error: FATAL EXCEPTION [main]
08-28 11:29:26.937  1097  1097 E AndroidRuntime: Unity version     : 2017.1.0p5
08-28 11:29:26.937  1097  1097 E AndroidRuntime: Device model      : Google Pixel
08-28 11:29:26.937  1097  1097 E AndroidRuntime: Device fingerprint: google/sailfish/sailfish:7.1.2/NJH47F/4146041:user/release-keys
08-28 11:29:26.937  1097  1097 E AndroidRuntime:
08-28 11:29:26.937  1097  1097 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void com.google.vr.audio.DeviceInfo.nativeUpdateHeadphoneStateChange(long, int) (tried Java_com_google_vr_audio_DeviceInfo_nativeUpdateHeadphoneStateChange and Java_com_google_vr_audio_DeviceInfo_nativeUpdateHeadphoneStateChange__JI)
08-28 11:29:26.937  1097  1097 E AndroidRuntime: 	at com.google.vr.audio.DeviceInfo.nativeUpdateHeadphoneStateChange(Native Method)
08-28 11:29:26.937  1097  1097 E AndroidRuntime: 	at com.google.vr.audio.DeviceInfo.a(PG:36)
08-28 11:29:26.937  1097  1097 E AndroidRuntime: 	at ala.onReceive(PG:7)
08-28 11:29:26.937  1097  1097 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
08-28 11:29:26.937  1097  1097 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
08-28 11:29:26.937  1097  1097 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-28 11:29:26.937  1097  1097 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
08-28 11:29:26.937  1097  1097 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
08-28 11:29:26.937  1097  1097 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-28 11:29:26.937  1097  1097 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
08-28 11:29:26.937  1097  1097 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
08-28 11:29:26.941  1103 28042 W ActivityManager:   Force finishing activity com.rpgiagames.mygamevr/com.unity3d.player.UnityPlayerActivity
08-28 11:29:26.953  1103 28042 W ActivityManager:   Force finishing activity com.rpgiagames.mygamevr/com.unity3d.player.UnityPlayerActivity
08-28 11:29:26.954  1103 28042 W ActivityManager: Duplicate finish request for ActivityRecord{4efe147 u0 com.rpgiagames.mygamevr/com.unity3d.player.UnityPlayerActivity t10704 f}
08-28 11:29:26.957  1097  1128 I Unity   : Calling set input mode: DEFAULT
08-28 11:29:26.957  1097  1128 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
08-28 11:29:26.957  1097  1128 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
08-28 11:29:26.957  1097  1128 I Unity   : UnityEngine.Logger:Log(LogType, Object)
08-28 11:29:26.957  1097  1128 I Unity   : UnityEngine.Debug:Log(Object)
08-28 11:29:26.957  1097  1128 I Unity   : Gvr.Internal.AndroidNativeKeyboardProvider:SetInputMode(GvrKeyboardInputMode) (at /Users/andrelevi/Workspace/vr/MyGame/Assets/GoogleVR/Scripts/Keyboard/Internal/KeyboardProviders/AndroidNativeKeyboardProvider.cs:159)
08-28 11:29:26.957  1097  1128 I Unity   : GvrKeyboard:Start() (at /Users/andrelevi/Workspace/vr/MyGame/Assets/GoogleVR/Scripts/Keyboard/GvrKeyboard.cs:150)
08-28 11:29:26.957  1097  1128 I Unity   :
08-28 11:29:26.957  1097  1128 I Unity   : (Filename: /Users/andrelevi/Workspace/vr/MyGame/Assets/GoogleVR/Scripts/Keyboard/Internal/KeyboardProviders/AndroidNativeKeyboardProvider.cs Line: 159)
08-28 11:29:26.957  1097  1128 I Unity   :
08-28 11:29:27.073  1103  1788 I OpenGLRenderer: Initialized EGL, version 1.4
08-28 11:29:27.073  1103  1788 D OpenGLRenderer: Swap behavior 1
08-28 11:29:27.255  1103  1103 I VrManagerService: VR mode disabled
```

Restarting fixes this issue for some reason, every time.

**Comment by martinbilello** [comment]
Thanks for reporting this, it is very helpful. We'll work on it, if you have any more tips for reproducing it, please post it here. Thanks!

**Comment by andrelevi** [comment]
Thanks for looking into this! I'm working on a multiplayer game where users need the keyboard to enter in a custom game name and chat with others via text, so having a working keyboard is pretty crucial for me.

Also, it appears that restarting my phone does not always fix the issue. I'm going to try experimenting with loading up the default Daydream app first, and whatever other things I can think of.

Since restarting my phone seems to *sometimes* fix the issue, I'm wondering if maybe the native keyboard process is not getting cleaned up properly after closing an app that uses the DD keyboard? Atm, I'm manually killing Daydream apps by going to the Android app list and swiping right on the app.

Here is an extended logcat when crashing at start due to the GvrKeyboard being enabled:

```
08-29 13:57:31.631  7202  7223 D AudioTrack: Client defaulted notificationFrames to 192 for frameCount 384
08-29 13:57:31.704  7202  7202 E art     : No implementation found for void com.google.vr.audio.DeviceInfo.nativeUpdateHeadphoneStateChange(long, int) (tried Java_com_google_vr_audio_DeviceInfo_nativeUpdateHeadphoneStateChange and Java_com_google_vr_audio_DeviceInfo_nativeUpdateHeadphoneStateChange__JI)
08-29 13:57:31.706  7202  7202 D AndroidRuntime: Shutting down VM
08-29 13:57:31.707  7202  7202 E AndroidRuntime: FATAL EXCEPTION: main
08-29 13:57:31.707  7202  7202 E AndroidRuntime: Process: com.google.vr.unity.gvrdemo, PID: 7202
08-29 13:57:31.707  7202  7202 E AndroidRuntime: java.lang.Error: FATAL EXCEPTION [main]
08-29 13:57:31.707  7202  7202 E AndroidRuntime: Unity version     : 2017.1.0p3
08-29 13:57:31.707  7202  7202 E AndroidRuntime: Device model      : Google Pixel
08-29 13:57:31.707  7202  7202 E AndroidRuntime: Device fingerprint: google/sailfish/sailfish:7.1.2/NJH47F/4146041:user/release-keys
08-29 13:57:31.707  7202  7202 E AndroidRuntime:
08-29 13:57:31.707  7202  7202 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void com.google.vr.audio.DeviceInfo.nativeUpdateHeadphoneStateChange(long, int) (tried Java_com_google_vr_audio_DeviceInfo_nativeUpdateHeadphoneStateChange and Java_com_google_vr_audio_DeviceInfo_nativeUpdateHeadphoneStateChange__JI)
08-29 13:57:31.707  7202  7202 E AndroidRuntime: 	at com.google.vr.audio.DeviceInfo.nativeUpdateHeadphoneStateChange(Native Method)
08-29 13:57:31.707  7202  7202 E AndroidRuntime: 	at com.google.vr.audio.DeviceInfo.a(PG:36)
08-29 13:57:31.707  7202  7202 E AndroidRuntime: 	at ala.onReceive(PG:11)
08-29 13:57:31.707  7202  7202 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
08-29 13:57:31.707  7202  7202 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
08-29 13:57:31.707  7202  7202 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-29 13:57:31.707  7202  7202 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
08-29 13:57:31.707  7202  7202 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
08-29 13:57:31.707  7202  7202 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-29 13:57:31.707  7202  7202 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
08-29 13:57:31.707  7202  7202 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
08-29 13:57:31.712  1114  2258 W ActivityManager:   Force finishing activity com.google.vr.unity.gvrdemo/com.unity3d.player.UnityPlayerActivity
08-29 13:57:31.717  7202  7202 I Process : Sending signal. PID: 7202 SIG: 9
08-29 13:57:31.743  1880  1880 I WCNSS_FILTER: ibs_msm_serial_clock_vote: vote UART CLK OFF using UART driver's ioctl()
08-29 13:57:31.748  1114  1411 W InputDispatcher: channel 'eb1d0e6 com.google.vr.unity.gvrdemo/com.unity3d.player.UnityPlayerActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
08-29 13:57:31.748  1114  6646 I WindowManager: WIN DEATH: Window{eb1d0e6 u0 com.google.vr.unity.gvrdemo/com.unity3d.player.UnityPlayerActivity}
08-29 13:57:31.748  1114  1409 I sensors : batch
08-29 13:57:31.748  1114  1131 I ActivityManager: Process com.google.vr.unity.gvrdemo (pid 7202) has died
08-29 13:57:31.748  1114  1131 D ActivityManager: cleanUpApplicationRecord -- 7202
08-29 13:57:31.749  2298  6358 I DaydreamManagerImpl: Daydream client died for: ComponentInfo{com.google.vr.unity.gvrdemo/com.unity3d.player.UnityPlayerActivity}
08-29 13:57:31.749  2298  6358 W DaydreamManagerImpl: Displaying crash notification for: ComponentInfo{com.google.vr.unity.gvrdemo/com.unity3d.player.UnityPlayerActivity}
08-29 13:57:31.749  2298  2318 I ControllerService: Removing listener 10155:7202:com.google.vr.internal.controller.LISTENER_KEY for controller 0.
08-29 13:57:31.749  1114  1411 E InputDispatcher: channel 'eb1d0e6 com.google.vr.unity.gvrdemo/com.unity3d.player.UnityPlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
08-29 13:57:31.749  1114  1409 I nanohub : queueBatch: sensor=8, handle=24, period=20000000, latency=0
08-29 13:57:31.749   508   508 W AudioFlinger::EffectModule: EffectModule 0xe7520a80 destructor called with unreleased interface
08-29 13:57:31.749  1114  6646 W InputDispatcher: Attempted to unregister already unregistered input channel 'eb1d0e6 com.google.vr.unity.gvrdemo/com.unity3d.player.UnityPlayerActivity (server)'
08-29 13:57:31.749   508   508 W AudioFlinger::EffectModule: EffectModule 0xe8798d00 destructor called with unreleased interface
08-29 13:57:31.750  1114  6646 W WindowManager: Force-removing child win Window{d0aee97 u0 SurfaceView - com.google.vr.unity.gvrdemo/com.unity3d.player.UnityPlayerActivity} from container Window{eb1d0e6 u0 com.google.vr.unity.gvrdemo/com.unity3d.player.UnityPlayerActivity}
08-29 13:57:31.750  1880  1880 I WCNSS_FILTER: ibs_msm_serial_clock_vote: vote UART CLK ON using UART driver's ioctl()
08-29 13:57:31.750  1114  1409 I sensors : batch
08-29 13:57:31.751  1114  1409 I nanohub : queueBatch: sensor=1, handle=1, period=2500000, latency=0
08-29 13:57:31.752  1114  1409 I sensors : batch
08-29 13:57:31.754  1114  1409 I nanohub : queueBatch: sensor=6, handle=25, period=2500000, latency=0
08-29 13:57:31.756  1114  6646 W WindowManager: Force-removing child win Window{223c884 u0 SurfaceView - com.google.vr.unity.gvrdemo/com.unity3d.player.UnityPlayerActivity} from container Window{eb1d0e6 u0 com.google.vr.unity.gvrdemo/com.unity3d.player.UnityPlayerActivity}
08-29 13:57:31.765  1114  6645 W WindowManager: Failed looking up window
08-29 13:57:31.765  1114  6645 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@ba3ccf7 does not exist
08-29 13:57:31.765  1114  6645 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9415)
08-29 13:57:31.765  1114  6645 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9406)
08-29 13:57:31.765  1114  6645 W WindowManager: 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1800)
08-29 13:57:31.765  1114  6645 W WindowManager: 	at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
08-29 13:57:31.765  1114  6645 I WindowManager: WIN DEATH: null
08-29 13:57:31.765  1114  6648 W WindowManager: Failed looking up window
08-29 13:57:31.765  1114  6648 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@b3bb764 does not exist
08-29 13:57:31.765  1114  6648 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9415)
08-29 13:57:31.765  1114  6648 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9406)
08-29 13:57:31.765  1114  6648 W WindowManager: 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1800)
08-29 13:57:31.765  1114  6648 W WindowManager: 	at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
08-29 13:57:31.765  1114  6648 I WindowManager: WIN DEATH: null
08-29 13:57:31.786  1114  1408 I sensors : batch
08-29 13:57:31.788  1114  1408 I nanohub : queueBatch: sensor=1, handle=1, period=2500000, latency=0
08-29 13:57:31.808   508   543 W AudioFlinger: session id 185 not found for pid 7202
08-29 13:57:31.808   508   543 W AudioFlinger::EffectHandle: disconnect Effect handle 0xe87a03c0 disconnected after thread destruction
08-29 13:57:31.808   508   543 W AudioFlinger: session id 217 not found for pid 7202
08-29 13:57:31.808   508   543 W AudioFlinger::EffectHandle: disconnect Effect handle 0xe878ce40 disconnected after thread destruction
08-29 13:57:31.809  1114  4027 I ActivityManager: Config changes=480 {1.0 310mcc410mnc [en_US] ldltr sw411dp w411dp h659dp 420dpi nrml port finger -keyb/v/h -nav/h s.13}
08-29 13:57:31.814  1114  1412 I InputReader: Reconfiguring input devices.  changes=0x00000004
08-29 13:57:31.814  1114  1412 I InputReader: Device reconfigured: id=6, name='qbt1000_key_input', size 1080x1920, orientation 0, mode 4, display id 0
08-29 13:57:31.814  1114  1412 I InputReader: Device reconfigured: id=9, name='synaptics_dsxv26', size 1080x1920, orientation 0, mode 1, display id 0
08-29 13:57:31.824  1114  2292 W AppOps  : Finishing op nesting under-run: uid 10072 pkg com.google.vr.vrcore code 24 time=0 duration=0 nesting=0
08-29 13:57:31.876  2655  2655 I DURecorder: {main}[DuRecorderApplication] onConfigurationChanged:
08-29 13:57:31.885  2298  2298 I cli     : Ui Overlay view reset
08-29 13:57:31.900  2565  2565 I DURecorder: {main}[DuRecorderApplication] onConfigurationChanged:
08-29 13:57:31.911  1114  1687 W AppOps  : Finishing op nesting under-run: uid 10072 pkg com.google.vr.vrcore code 24 time=0 duration=0 nesting=0
08-29 13:57:31.958  2298  2298 I cli     : Ui Overlay view reset
08-29 13:57:32.052  2365  2365 E LegacyNowServiceClient: skipping logEndstates, service is null
08-29 13:57:32.078  1114  1114 I VrManagerService: VR mode disabled
```

**Comment by xiaotaoduan** [comment]
Hi Andre,
Thanks for reporting this issue! It will be fixed in next Daydream keyboard release.

**Comment by andrelevi** [comment]
Thank you! I'm so glad to hear this. I was seeing this issue on both my Galaxy S8 and Pixel, and was (reluctantly) considering implementing my own in-game keyboard. Great news!

**Comment by fredsa** [comment]
This issue was fixed by an update to the [Daydream Keyboard](https://play.google.com/store/apps/details?id=com.google.android.vr.inputmethod) app.
