### ISSUE TITLE
Please let us know, how to use GvrVideoTexture with external video file for android.

### ISSUE THREAD

**Issue by sejin1park** [googlevr/gvr-unity-sdk#762]
<Brief summary of the issue you encountered>

Found using:
 * Google VR SDK version: __1.70.0
 * Unity version: _2017.1.1f, __
 * Phone manufacturer, model, and O/S version: __Samsung Galaxy S4  _  android 5.0

Please let me know, how to play external (SD card) video file in android. 
I can use Video Player to access and play external video via script with Application.persistentDataPath + "/movie/1.mp4” format.  

However, if I use GvrVideoTexture with same path, it is no use, and just kill the application.

Steps to reproduce the issue:
1.Write Permission has been changed to  External.
2.Changed panoVideoSample Type to other in GoogleVR's VideoDemo,   set to ${Application.persistentDataPath}/movie/1.mp4 
3.In ProcessURL(), changed return videoURL.Replace("${Application.persistentDataPath}", Application.persistentDataPath); 
( Changed path for return )

Android logcat is as follows : 

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
at com.google.gvr.exoplayersupport.sample.ExtractorRendererBuilder.init(ExtractorRendererBuilder.java:71)
at com.google.gvr.exoplayersupport.sample.VideoExoPlayer.initPlayer(VideoExoPlayer.java:315)
at com.google.gvr.exoplayersupport.sample.VideoExoPlayer.access$200(VideoExoPlayer.java:54)
at com.google.gvr.exoplayersupport.sample.VideoExoPlayer$1.run(VideoExoPlayer.java:146)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at com.google.gvr.exoplayersupport.sample.VideoExoPlayer$VideoLooperThread.run(VideoExoPlayer.java:881)

**Comment by dsternfeld7** [comment]
I believe it needs to be "file://" + <full path to the file>

The [Media App Template](https://developers.google.com/vr/unity/media-app-template) uses the Gvr Video Plugin to play videos located in external storage, so I would recommend looking at that as an example.

[Here](https://github.com/googlevr/media-app-template/blob/master/Assets/MediaAppTemplate/Scripts/UI/FileSelector/MediaSelector.cs) is one of the most relevant files.

Thanks,

Dan

**Comment by nathanmartz** [comment]
Closing as I believe this is the issue. Please reopen if not.

**Comment by sejin1park** [comment]
Very appreciate your kind assistance.  I missed "file://" for external ones.
