### ISSUE TITLE
Video stops playing but audio keeps going

### ISSUE THREAD

**Issue by Tripwire999** [googlevr/gvr-unity-sdk#846]
<Brief summary of the issue you encountered>

Found using:
 * Google VR SDK version: v1.120.0
 * Unity version: 2017.3.0f3
 * Phone manufacturer, model, and O/S version: Google Pixel 2 with Android 8.1.0 (same problem also occurs on Android 8.0)
 * Viewer manufacturer & model: Google Daydream

I'm having an issue with the GVRVideoPlayerTexture where the video stops playing due to buffering but the audio keeps playing. So we have over 20 scenes each with a GoogleVR setup and using a sphere with a GVRVideoPlayerTexture script attached which points to a 4k stereoscopic vr video (around 700MB / 800MB). The first time the video is played everything works fine. The user navigates to the next scene and then almost always the video stops playing at around 0:03 seconds (the picture stops moving) but the audio keeps playing. It seems to happen sometimes with the first video played as well. There are no errors in the Android logcat or in the Unity3D console. 
I've tried debugging it by putting a Debug.Log statement in the Update() method of the GvrVideoPlayerTexture.cs class and debugging the BufferedPosition and as I assumed this not updated with a new value. It's like it just stops buffering all together. 
The only way for the user to fix it for now is use our rewind feature in our video controls to rewind the video to the beginning and press play again. Then everything works fine and the video + audio keeps playing.

During development I did change the following:
Instead of loading the video from the StreamingAssets i'm loading the video from a folder on the sdcard of the Google Pixel by calling the following code:

`string videoURL = "file://" + GetAndroidInternalFilesDir() + "/PVMMovies/" + videoName;
Debug.Log("Trying to load video: " + videoURL);
gvrVideoPlayerTexture.videoURL = videoURL;`

GetAndroidInternalFilesDir basically returns the SDCard directory on the device. The videoName is returned from a database. This script is executed **before** the GVRVideoPlayer script initializes.

**Comment by Neogene** [comment]
Maybe is a similar problem, in my case playing a video stored in local folder (not streaming) first time fails due to end of file exception, then it restarts automatically and works well..

02-07 10:12:24.619 16536-16926/it.leganza.VR360 E/VideoExoPlayer: raising exception to listeners
    java.io.EOFException
        at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:394)
        at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:255)
        at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:403)
        at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:134)
        at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:835)
        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Comment by chaosemer** [comment]
Could you please share a project that reproduces this issue with us? Thanks.

**Comment by fredsa** [comment]
Close due to inactivity.
